import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "reflect-metadata"
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          this is header
          {/* <ul>
            <li>首页</li>
            <li>页面</li>
          </ul> */}
        </header>
        <main>
          main
        {children}
        </main>
        <footer>i am footer</footer>
      </body>
    </html>
  )
}
